sudo: required

services:
  - docker

before_install:
  - docker build -t tfah/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tfah/react-test npm test

after_success:
  - docker build -t tfah/multi-client ./client
  - docker build -t tfah/multi-nginx ./nginx
  - docker build -t tfah/multi-server ./server
  - docker build -t tfah/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tfah/multi-client
  - docker push tfah/multi-nginx
  - docker push tfah/multi-server
  - docker push tfah/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-076744648477
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY